# Application properties for Identity Service

#Flyway properties
spring.flyway.enabled=true
spring.flyway.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-identity:5432/tickon_identity}
spring.flyway.password=${DB_PASSWORD:postgres}
spring.flyway.user=${DB_USER:postgres}
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration
