spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/api/identity/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus